// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/get-my-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.2";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/get-my-profile.ts
var get_my_profile_default = defineTool({
  name: "get_my_profile",
  title: "Get my Pique profile",
  description: "Get the signed-in player's Pique profile: Pique IQ rating, games played and won, current and best streak, and per-mode game counts.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("profiles").select(
      "display_name, rating, games_played, games_won, current_streak, best_streak, games_played_klondike, games_played_freecell, games_played_realm, daily_challenge_completed_today"
    ).eq("id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "No profile found." }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/tools/list-recent-games.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";
var list_recent_games_default = defineTool2({
  name: "list_recent_games",
  title: "List my recent games",
  description: "List the signed-in player's most recent Pique games with mode, difficulty, result, time, moves and Pique IQ change.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).default(10).describe("How many games to return (1-50)."),
    game_mode: z.enum(["klondike", "freecell", "realm"]).optional().describe("Optional filter for a single game mode.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, game_mode }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("game_history").select(
      "played_at, game_mode, difficulty, won, time_seconds, moves, hints_used, rating_change, rating_after, is_daily_challenge"
    ).eq("user_id", ctx.getUserId()).order("played_at", { ascending: false }).limit(limit ?? 10);
    if (game_mode) query = query.eq("game_mode", game_mode);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { games: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-mode-stats.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_mode_stats_default = defineTool3({
  name: "get_mode_stats",
  title: "Get my stats by game mode",
  description: "Summarise the signed-in player's Pique performance per game mode: games played, wins, win rate, average time and moves, and net Pique IQ change.",
  inputSchema: {
    since_days: z2.number().int().min(1).max(365).optional().describe("Only include games played in the last N days.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ since_days }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("game_history").select("game_mode, won, time_seconds, moves, rating_change").eq("user_id", ctx.getUserId()).limit(2e3);
    if (since_days) {
      const since = new Date(Date.now() - since_days * 864e5).toISOString();
      query = query.gte("played_at", since);
    }
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = data ?? [];
    const byMode = {};
    for (const row of rows) {
      const key = row.game_mode ?? "unknown";
      const acc = byMode[key] ??= { games: 0, wins: 0, totalTime: 0, totalMoves: 0, netIQ: 0 };
      acc.games += 1;
      if (row.won) acc.wins += 1;
      acc.totalTime += row.time_seconds ?? 0;
      acc.totalMoves += row.moves ?? 0;
      acc.netIQ += row.rating_change ?? 0;
    }
    const stats = Object.entries(byMode).map(([mode, a]) => ({
      game_mode: mode,
      games: a.games,
      wins: a.wins,
      win_rate: a.games ? Math.round(a.wins / a.games * 1e3) / 10 : 0,
      avg_time_seconds: a.games ? Math.round(a.totalTime / a.games) : 0,
      avg_moves: a.games ? Math.round(a.totalMoves / a.games) : 0,
      net_iq_change: a.netIQ
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(stats, null, 2) }],
      structuredContent: { stats }
    };
  }
});

// src/lib/mcp/tools/get-daily-challenge.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var get_daily_challenge_default = defineTool4({
  name: "get_daily_challenge",
  title: "Get the daily challenge",
  description: "Get Pique's daily challenge for a given date (today by default): game mode and difficulty, plus the signed-in player's result if they have played it.",
  inputSchema: {
    date: z3.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("Date in YYYY-MM-DD format. Defaults to today (UTC).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ date }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const day = date ?? (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const { data: challenge, error } = await supabase.from("daily_challenges").select("id, date, game_mode, difficulty").eq("date", day).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!challenge) {
      return { content: [{ type: "text", text: `No daily challenge found for ${day}.` }] };
    }
    const { data: result } = await supabase.from("daily_challenge_results").select("*").eq("challenge_id", challenge.id).eq("user_id", ctx.getUserId()).maybeSingle();
    const payload = { challenge, my_result: result ?? null };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "habzaxkukdlllwlavpdc";
var mcp_default = defineMcp({
  name: "pique",
  title: "Pique",
  version: "0.1.0",
  instructions: "Tools for Pique, a puzzle app with Klondike, FreeCell and Realm modes rated by a composite 'Pique IQ'. Use get_my_profile for the player's rating and streaks, list_recent_games for their recent games, get_mode_stats for per-mode performance summaries, and get_daily_challenge for today's challenge and the player's result. All tools act as the signed-in player.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_my_profile_default, list_recent_games_default, get_mode_stats_default, get_daily_challenge_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
