// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://habzaxkukdlllwlavpdc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhhYnpheGt1a2RsbGx3bGF2cGRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM5Mjg0NDcsImV4cCI6MjA4OTUwNDQ0N30.uFXCok5Q08jZZRwT84uxHez7FHX0wFpDhrhy1vr8bSY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});